### ISSUE TITLE
setup.py file to install modules as library

### ISSUE THREAD

**Issue by mathematicalmichael** [Calvinxc1/PrincoML#1]
Any interest in such a contribution?

**Comment by Calvinxc1** [comment]
Once I learn exactly how those work, sure (-:

**Comment by mathematicalmichael** [comment]
I would make sure to add instructions to the `README`, but essentially the flow would be:

`git clone https://github.com/Calvinxc1/libraryname`
`cd libraryname`
`python setup.py install`
which creates a `/build` folder with the compiled versions of your python code. These will get called when you import the library. 

and then you can simply `import libraryname as xx` in your files instead of having those long headers in the first cells of your jupyter notebooks.

One `setup.py` gets added that has details about the repository name, contact info, version, etc.

Thing is, once it’s done, it’s pretty easy to see how to edit things and add modules, learning from the ground up… not even sure what to look up to be honest… it’s been a while, but “how to add module setup.py” should get you most of what you need.

**Comment by Calvinxc1** [comment]
The long headers are still gonna be needed as when I'm working on code I like to import the component classes individually. Going with the defaults likely wouldn't need as much, but part of me futzing around with this is to find the defaults (-:

Still though, if you think you can do it, go for it!

**Comment by mathematicalmichael** [comment]
ah, so then the only real upside then is if you want to use these notebooks on another computer without cloning the repo (or move your notebooks around to different locations). Installing a module this way makes it accessible from anywhere on the computer. But if you work solely out of this directory and have no other users, not much upside.

that said, I can introduce this package to ~20 students and have them start trying to use it for their own problems, but it’d have to be in a state ready for contributions; ready for you to let others use it. What’s nice is that it’s a little less black-boxy, so students can learn something about implementation, make tweaks, etc.

**Comment by Calvinxc1** [comment]
It's not too painful to use as-is, cloning the repo and modifying the testbed notepads works fairly well. Feel free to run it by your students. I'm happy to start getting outside feedback/contributions/ideas/etc. even with the state the code's in currently.

I'm glad it's not as painfully black-boxy as other libraries, as I really hate how behind-the-scenes those are.

**Comment by Calvinxc1** [comment]
Any interest in working on this? It's not something I'm familiar enough to do.

**Comment by mathematicalmichael** [comment]
what would you like the library to be called? 
Pick a name that isn't taken on https://pypi.org/, rename both the repository and the folder `ml_lib` to match that name. 
For example, the package [`BET`](https://github.com/UT-CHG/BET) has all its methods in the folder called `bet`.

**Comment by Calvinxc1** [comment]
Crap, I have to make a decision? Erm... shit... I need to think about that... Gimmie a few days to figure out a halfway decent name...

**Comment by mathematicalmichael** [comment]
> Crap, I have to make a decision? Erm... shit... I need to think about that... Gimmie a few days to figure out a halfway decent name...

sorry! but yeah, you'll have to pick some sort of available name to make it publishable. 
good news is that once that kind of stuff is set up, I'll show you some cool possibilities (like, being able to run your code without having access to your laptop).

**Comment by mathematicalmichael** [comment]
- [x] choose name
- [x] pre-clean code (linting)
- [x] `setup.py` file
- [ ] `requirements.txt` file
- [ ] unit tests ⚠️
- [ ] Travis CI
- [ ] Hound
- [x] publish to PyPi? (`pip install` ability) 
- [ ] update `README` to reflect new installation instructions
- [ ] `CONTRIBUTING` file to serve as checklist for how to properly submit a PR to this repo
- [ ] add build status badge, binder badge to `README`

**Comment by Calvinxc1** [comment]
Alright, name chosen, and the linting changes are accepted. I've been treating the '_testbed' notebooks as my pseudo-unit-tests to date. Is there a more formal way I should take?

**Comment by Calvinxc1** [comment]
Additional item: If we're gonna set this up as a proper library I definitely want it accessible via Conda.

**Comment by mathematicalmichael** [comment]
> Alright, name chosen, and the linting changes are accepted. I've been treating the '_testbed' notebooks as my pseudo-unit-tests to date. Is there a more formal way I should take?

Yes. 
`unittest` or `nose`, both fairly straightforward. 
https://nose.readthedocs.io/en/latest/writing_tests.html

> Additional item: If we're gonna set this up as a proper library I definitely want it accessible via Conda.


once we can ensure the full continuous-integration cycle and have tests written, publishing it to `conda-forge` won't be hard. with pip, pushing frequent updates is easy/encouraged. not so for conda. you have to submit your code for testing across multiple platforms before it gets published.  https://conda-forge.org/#add_recipe 
furthermore, having it already pre-published on PyPi helps in the conda publishing process https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-recipe-meta-yaml
there's a decent amount to learn just for that goal, so I would encourage you to open up a separate issue solely to track the TO-DOs of publishing to conda-forge.

**Comment by Calvinxc1** [comment]
I've created a monster (-: Alright, will start poking around at that when I have time.

**Comment by mathematicalmichael** [comment]
open source is amazing. once you learn it, doing it from the ground-up changes everything. 
I've been at it for years and am finally recognizing the value in all of it (now that I'm working on a DOE-sponsored repository with other people). continuous integration specifically is of paramount importance for reproducibility, and it relies on testing. =)

**Comment by Calvinxc1** [comment]
Ooh definitely I love all your putting in here, to be sure, but there's no doubt that it's gonna be a slow burn for me to find the time to work on this properly (-:

**Comment by Calvinxc1** [comment]
#5 and #6 to complete this. Other indicated features will be included in future pre 1.0 releases.
